// flow-typed signature: cdb8d90ca4d08aad6d5e557af94dc4d5
// flow-typed version: <<STUB>>/rollup-plugin-image_v^1.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-image/dist/rollup-plugin-image.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-image/dist/rollup-plugin-image.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-image/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-image/dist/rollup-plugin-image.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-image/dist/rollup-plugin-image.cjs'>;
}
declare module 'rollup-plugin-image/dist/rollup-plugin-image.es.js' {
  declare module.exports: $Exports<'rollup-plugin-image/dist/rollup-plugin-image.es'>;
}
declare module 'rollup-plugin-image/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-image/src/index'>;
}
