// flow-typed signature: 06aec3d2a28b6e7c4fd4870413fc4bb8
// flow-typed version: <<STUB>>/to-case_v^2.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-case/lib/cases' {
  declare module.exports: any;
}

declare module 'to-case/lib/index' {
  declare module.exports: any;
}

declare module 'to-case/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-case/lib/cases.js' {
  declare module.exports: $Exports<'to-case/lib/cases'>;
}
declare module 'to-case/lib/index.js' {
  declare module.exports: $Exports<'to-case/lib/index'>;
}
declare module 'to-case/test/index.js' {
  declare module.exports: $Exports<'to-case/test/index'>;
}
